### ISSUE TITLE
NPM Install Issue

### ISSUE THREAD

**Issue by tehmufifnman** [mwojtkowski/Ovale#18]
When I run `npm install` and it tries to execute `tstolua -p tsconfig.lua.json` I get these errors

- Error E:/Dropbox/Projects/Ovale/Ovale-mwojtkowski/src/Equipment.ts (6,30): Module '"E:/Dropbox/Projects/Ovale/Ovale-mwojtkowski/node_modules/@wowts/wow-mock/index"' has no exported member 'GetItemInfoInstant'.
- Error E:/Dropbox/Projects/Ovale/Ovale-mwojtkowski/src/Equipment.ts (313,35): Type 'void' cannot be used as an index type.
- Error E:/Dropbox/Projects/Ovale/Ovale-mwojtkowski/src/PaperDoll.ts (10,261): Module '"E:/Dropbox/Projects/Ovale/Ovale-mwojtkowski/node_modules/@wowts/wow-mock/index"' has no exported member 'UnitRangedDamage'.

**Comment by mwojtkowski** [comment]
Sidoine just merged my pull request that adds missing functions, please update wow-mock to newest version ^1.4.0

**Comment by tehmufifnman** [comment]
thank you!
