### ISSUE TITLE
TypeScript Errors

### ISSUE THREAD

**Issue by tehmufifnman** [mwojtkowski/Ovale#19]
When running the tsc command, I get the following errors

> PS E:\Dropbox\Projects\Ovale\Ovale-mwojtkowski> tsc
> node_modules/@wowts/ace_config-3.0/index.ts:1:1 - error TS6192: All imports in import declaration are unused.
> 
> 1 import { Constructor, Library} from "@wowts/tslib";
> node_modules/@wowts/ace_db-3.0/index.ts:2:1 - error TS6192: All imports in import declaration are unused.
> 2 import { Constructor, Library} from "@wowts/tslib";
> node_modules/@wowts/ace_db_options-3.0/index.ts:2:1 - error TS6192: All imports in import declaration are unused.
> 2 import { LuaObj, pairs } from "@wowts/lua";
> node_modules/@wowts/ace_db_options-3.0/index.ts:3:1 - error TS6192: All imports in import declaration are unused.
> 3 import { Constructor, Library} from "@wowts/tslib";
> node_modules/@wowts/ace_gui-3.0/index.ts:2:1 - error TS6133: 'AceModule' is declared but its value is never read.
> 2 import { AceModule } from "@wowts/tsaddon";
> node_modules/@wowts/ace_gui-3.0/index.ts:3:1 - error TS6192: All imports in import declaration are unused.
> 3 import { Constructor, Library } from "@wowts/tslib";
> node_modules/@wowts/ace_serializer-3.0/index.ts:1:1 - error TS6133: 'AceModule' is declared but its value is never read.
> 1 import { AceModule } from "@wowts/tsaddon";
> node_modules/@wowts/ace_timer-3.0/index.ts:1:1 - error TS6133: 'AceModule' is declared but its value is never read.
> 1 import { AceModule } from "@wowts/tsaddon";
> node_modules/@wowts/lib_text_dump-1.0/index.ts:3:25 - error TS6138: Property 'name' is declared but its value is never read.
> 3     constructor(private name: string, private width: number, private height: number) {}
> node_modules/@wowts/lib_text_dump-1.0/index.ts:3:47 - error TS6138: Property 'width' is declared but its value is never read.
> 3     constructor(private name: string, private width: number, private height: number) {}
> node_modules/@wowts/lib_text_dump-1.0/index.ts:3:70 - error TS6138: Property 'height' is declared but its value is never read.
> 3     constructor(private name: string, private width: number, private height: number) {}
> src/SimulationCraft.ts:4235:9 - error TS6133: 'specialization' is declared but its value is never read.
> 4235     let specialization = annotation.specialization;
> src/SpellBook.ts:6:62 - error TS6133: 'LuaArray' is declared but its value is never read.
> 6 import { ipairs, pairs, tonumber, tostring, wipe, lualength, LuaArray } from "@wowts/lua";

It does seem to successfully create the dist/utils folder though.

When I try and run `npm run simc` I get the following error.

> PS E:\Dropbox\Projects\Ovale\Ovale-mwojtkowski> npm run simc
> 
> > ovale@8.0.0 simc E:\Dropbox\Projects\Ovale\Ovale-mwojtkowski
> > node dist/utils/importsimc.js ../../simc
> E:\Dropbox\Projects\Ovale\Ovale-mwojtkowski\dist\utils\importspells.js:51
>                 throw new Error(`Unexcepted ${$data[i]} character at ${$data.substring(i - 3)} in ${$data}`);
>                 ^
> Error: Unexcepted n character at ", nullptr  in  273150, 44, "Drustvar", nullptr
>     at getColumns (E:\Dropbox\Projects\Ovale\Ovale-mwojtkowski\dist\utils\importspells.js:51:23)
>     at readFile (E:\Dropbox\Projects\Ovale\Ovale-mwojtkowski\dist\utils\importspells.js:65:31)
>     at Object.getSpellData (E:\Dropbox\Projects\Ovale\Ovale-mwojtkowski\dist\utils\importspells.js:78:5)
>     at Object.<anonymous> (E:\Dropbox\Projects\Ovale\Ovale-mwojtkowski\dist\utils\importsimc.js:61:34)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

**Comment by mwojtkowski** [comment]
Errors you get are just warnings they won't cause any problems with npm run prepare
You can stop tsc from reporting unused variables by setting ```"noUnusedLocals": false``` in your tsconfig.lua.json or tsconfig.json

About second error, you're trying to use new importspell script that Sidoine is working on (WIP)
I took quick look at that error and what you have to do is change nullptr to "nullptr" or just empty string
so change line 955 in importspell.ts to look like this
```$line = $line.replace(/\/\/.*/, '').replace('nullptr', '');```

**Comment by tehmufifnman** [comment]
Thank you so much!  Do you know if Sidoine is taking back control of the project?  Or do you plan on continuing your work and updates?  It has been much appreciated!

**Comment by mwojtkowski** [comment]
He is working on it, he did merge changes from ShmooDude and me 2 days ago
I plan to update spells for few more classes ( that I have on 110 ) and do pull request

**Comment by tehmufifnman** [comment]
Fantastic!  If you (or whoever) can manage to keep Veng Demon Hunter updated - you will have my eternal gratitude.
